# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb0d96ff9a10c8ba30c753dac589ac3373a9c5fc6c1df85a4da819ca500aebc940424989bda7d9e33984848025599e5354f0cfe71944dd3aa0eb0275df776f7a

test:
  secret_key_base: 74be363ac16ff7a1af79f85f99a90752f2708fb42653b8d449682bb042bf8c379bb358ea441dceda46fd81b4ac7a8b238e3d7d6508477201bcdafba50bea28be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
